routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('deplacements', 'deplacementController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/deplacement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class deplacement extends Model
{
   protected $fillable = [
        'nom',
        'prenom',
        'email',
        'datedepart',
        'dateretour',
       'heuredepart',
       'heureretour'
    ];
public $timestamps = false;

}

app/moyen.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class moyen extends Model
{
    //
}

app/ville.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ville extends Model
{
    //
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/deplacementController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\deplacement;
class deplacementController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
          $deplacements = deplacement::all();

        return view('deplacements.index', compact('deplacements'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('deplacements.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nom'=>'required',
            'prenom'=>'required',
            'email'=>'required'
        ]);

        $deplacement = new deplacement([
            'nom' => $request->get('nom'),
            'prenom' => $request->get('prenom'),
            'email' => $request->get('email'),
            'datedepart' => $request->get('datedepart'),
            'dateretour' => $request->get('dateretour'),
            'heuredepart' => $request->get('heuredepart'),
            'heureretour' => $request->get('heureretour')
          
        ]);
        $deplacement->save();
        return redirect('/deplacements')->with('success', 'deplacement saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         $deplacement = deplacement::find($id);
        return view('deplacements.edit', compact('deplacement'));     
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $request->validate([
            'nom'=>'required',
            'prenom'=>'required',
            'email'=>'required'
        ]);

        $deplacement = deplacement::find($id);
        $deplacement->nom =  $request->get('nom');
        $deplacement->prenom = $request->get('prenom');
        $deplacement->email = $request->get('email');
        $deplacement->datedepart = $request->get('datedepart');
        $deplacement->dateretour = $request->get('dateretour');
        $deplacement->heuredepart = $request->get('heuredepart');
        $deplacement->heureretour = $request->get('heureretour');
        $deplacement->save();

        return redirect('/deplacements')->with('success', 'deplacement updated!');
    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $deplacement = deplacement::find($id);
        $deplacement->delete();

        return redirect('/deplacements')->with('success', 'deplacement deleted!');
    }
}

resources/views/base.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Laravel 5.8 & MySQL CRUD Tutorial</title>
  <link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css" />
</head>
<body>
  <div class="container">
    @yield('main')
  </div>
  <script src="{{ asset('js/app.js') }}" type="text/js"></script>
</body>
</html>

resources/views/deplacements/create.blade.php
@extends('base')

@section('main')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h4 class="display-3">ajouter deplacement</h4>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('deplacements.store') }}">
          @csrf
          <div class="form-group">    
              <label for="nom">Nom</label>
              <input type="text" class="form-control" name="nom"/>
          </div>

          <div class="form-group">
              <label for="prenom">prenom</label>
              <input type="text" class="form-control" name="prenom"/>
          </div>

          <div class="form-group">
              <label for="email">Email</label>
              <input type="text" class="form-control" name="email"/>
          </div>
          <div class="form-group">
              <label for="datedepart">date depart</label>
              <input type="date" class="form-control" name="datedepart"/>
          </div>
          <div class="form-group">
              <label for="dateretour">date retour:</label>
              <input type="date" class="form-control" name="dateretour"/>
          </div>
          <div class="form-group">
              <label for="heuredepart">heure depart:</label>
              <input type="time" class="form-control" name="heuredepart"/>
 <div class="form-group">
              <label for="heureretour">heure retour:</label>
              <input type="time" class="form-control" name="heureretour"/>
          </div>                         
          <button type="submit" class="btn btn-primary-outline">ajouter </button>
      </form>
  </div>
</div>
</div>
@endsection

resources/views/deplacements/edit.blade.php
@extends('base') 
@section('main')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Update a deplacement</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('deplacements.update', $deplacement->id) }}">
            @method('PATCH') 
            @csrf
            <div class="form-group">

                <label for="nom">nom:</label>
                <input type="text" class="form-control" name="nom" value={{ $deplacement->nom }} />
            </div>

            <div class="form-group">
                <label for="prenom">prenom:</label>
                <input type="text" class="form-control" name="prenom" value={{ $deplacement->prenom }} />
            </div>

            <div class="form-group">
                <label for="email">Email:</label>
                <input type="text" class="form-control" name="email" value={{ $deplacement->email }} />
            </div>
            <div class="form-group">
                <label for="datedepart">date depart:</label>
                <input type="date" class="form-control" name="datedepart" value={{ $deplacement->datedepart }} />
            </div>
            <div class="form-group">
                <label for="dateretour">date retour:</label>
                <input type="date" class="form-control" name="dateretour" value={{ $deplacement->dateretour }} />
            </div>
            <div class="form-group">
                <label for="heuredepart">heure depart:</label>
                <input type="time" class="form-control" name="heuredepart" value={{ $deplacement->heuredepart }} />
            </div>
 <div class="form-group">
                <label for="heureretour">heure retour:</label>
                <input type="time" class="form-control" name="heureretour" value={{ $deplacement->heureretour }} />
            </div>

            <button type="submit" class="btn btn-primary">Modifier</button>
        </form>
    </div>
</div>
@endsection

resources/views/deplacements/index.blade.php
@extends('base')

@section('main')
   <div>
    <a style="margin: 19px;" href="{{ route('deplacements.create')}}" class="btn btn-primary">New deplacement</a>
    </div>  
<div class="row">
<div class="col-sm-12">
    <h2 class="display-3">deplacements</h2>    
  <table class="table table-striped">
    <thead>
        <tr>
          <td>Nom</td>
          <td>prenom</td>
          <td>email</td>
          <td>datedepart</td>
          <td>dateretour</td>
          
          <td colspan = 2>Actions</td>
        </tr>
    </thead>
    <tbody>
        @foreach($deplacements as $deplacement)
        <tr>
            <td>{{$deplacement->nom}} <td>{{$deplacement->prenom}}</td>
            <td>{{$deplacement->email}}</td>
            <td>{{$deplacement->datedepart}}</td>
            <td>{{$deplacement->dateretour}}</td>
           
            <td>
                <a href="{{ route('deplacements.edit',$deplacement->id)}}" class="btn btn-primary">Edit</a>
            </td>
            <td>
                <form action="{{ route('deplacements.destroy', $deplacement->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
</div>
<div class="col-sm-12">

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
@endsection